# Generated by Django 5.2.4 on 2025-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_requestlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogs',
            name='request_method',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestlogs',
            name='request_type',
            field=models.CharField(max_length=100),
        ),
    ]
